// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "VtestScala.cpp"
#include "VtestScala___024root.cpp"
#include "VtestScala__Trace.cpp"
#include "VtestScala___024root__Slow.cpp"
#include "VtestScala__Syms.cpp"
#include "VtestScala__Trace__Slow.cpp"
